### ISSUE TITLE
Kafka sends (Key, Value) as a record, and only value is passed to Kinesis

### ISSUE THREAD

**Issue by acidburnburn** [awslabs/kinesis-kafka-connector#1]
Kafka sends (Key, Value) as a record, and only value is passed to Kinesis.
Key is lost forever. Cmon guys.

**Comment by jessecollier** [comment]
Hmm. Looks it is in fact sending the key...
https://github.com/awslabs/kinesis-kafka-connector/blob/master/src/main/java/com/amazon/kinesis/kafka/AmazonKinesisSinkTask.java#L85-L103

I'm interested in your testing as I'm wanting to implement this myself and also want to preserve the keys.

**Comment by nehalmehta** [comment]
@acidburnburn Can you share config used by you? It passes key from Kafka to Kinesis. I will re-create based on your config.

**Comment by acidburnburn** [comment]
Here is SinkRecord object http://apache.osuosl.org/kafka/0.10.0.1/javadoc/org/apache/kafka/connect/sink/SinkRecord.html

It has key and value. In the code you're passing only value, removing key:

f = kinesisProducer.addUserRecord(streamName, partitionKey,
						Integer.toString(sinkRecord.kafkaPartition()),
						DataUtility.parseValue(sinkRecord.valueSchema(), sinkRecord.value()));

**Comment by acidburnburn** [comment]
Re tests - it's nice to have parametric integration test, where you can specify kafka topic and kinesis stream and see if can push record to kafka and get the same one from kinesis.

**Comment by nehalmehta** [comment]
Thanks for the feedback. But partitionKey is initialized to Kafka Key here - https://github.com/awslabs/kinesis-kafka-connector/blob/master/src/main/java/com/amazon/kinesis/kafka/AmazonKinesisSinkTask.java#L85-L91.  Do you know if Kafka has non empty key in your use case? Or are you setting config usePartitionAsHashKey to true?

**Comment by jessecollier** [comment]
@nehalmehta 👍  on default false.

I've also modified for my own needs to have default blank kafka keys be randomized onto kinesis.
https://github.com/awslabs/kinesis-kafka-connector/compare/master...jessecollier:master

This provides me the ability to scale shards > partitions. 
Not sure if you'd be interested in merging this into the main code base.

**Comment by nehalmehta** [comment]
@jessecollier  thanks for the feedback. If you want to scale shards > partitions and also have round robin delivery to shards, it would be better to have following so that Key values are preserved. 

f = kinesisProducer.addUserRecord(streamName, partitionKey,
            Integer.toString(random.nextInt(partitionKeysCount)),
						DataUtility.parseValue(sinkRecord.valueSchema(), sinkRecord.value()));

**Comment by jessecollier** [comment]
@nehalmehta from what i understand the input from partitionKey will be hashed and used to put onto the shard. How does specifying the ExplictHashKey help me? In fact what does it do? Why do I need two "key" parameters?

**Comment by nehalmehta** [comment]
@jessecollier ExplicitHashKey is the hash value used to explicitly determine the shard the data record is assigned to by overriding the partition key hash. You can look at more information here - http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecord.html

**Comment by nehalmehta** [comment]
There is no evidence provided that shows keys are not processed as they should be and so closing the issue.
