### ISSUE TITLE
Java fails to convert object to KafkaTopic

### ISSUE THREAD

**Issue by cjbackman** [awslabs/kinesis-kafka-connector#34]
When the load is heavy enough to trigger the pausing/resuming of consumption the following error thrown:

```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.apache.kafka.common.TopicPartition;
```

This happens since the call to `toArray()` is used without explicitly specifying the type of the elements in the array.

See PR #31

**Comment by skidder** [comment]
@bdesert Can we get this PR merged? This issue continues to be a problem, and the fix has been working for me in my deployment. Thanks!
